apiVersion: batch/v1
kind: Job
metadata:
  name: chknorrjks-job
spec:
  template:
    spec:
      containers:
      - name: chknorrjks-job
        image: yash5090/chknorrjks:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
