apiVersion: apps/v1
kind: Deployment
metadata:
  name: chknorrjks-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: chknorrjks
  template:
    metadata:
      labels:
        app: chknorrjks
    spec:
      containers:
        - name: chknorrjks
          image: yash5090/chknorrjks:latest # Replace with the actual image tag
          ports:
            - containerPort: 5000 # Replace with the port your Tetris game listens on
